language: python
dist: xenial
python:
  - '3.7'
install:
  - pip install -r requirements.txt
  - echo $SSH_KEY >> $HOME/.ssh/known_hosts
script: ignore
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c5a4c176c827_key -iv $encrypted_c5a4c176c827_iv
    -in id_rsa.enc -out id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 id_rsa
  - ssh-add id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true
before_install:
  - openssl aes-256-cbc -K $encrypted_c5a4c176c827_key -iv $encrypted_c5a4c176c827_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
