version: "3"




services:
  database:
    hostname: "postgres"
    container_name: "iceteabot-postgres"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: iceteabot
      POSTGRES_USER: iceteabot
      POSTGRES_PASSWORD: Iceteabot

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iceteabot
  iceteabot:
    hostname: "iceteabot"
    container_name: "iceteabot-container"
    build: .
    depends_on:
      - database
    environment:
      - DISCORD_TOKEN
      - POSTGRES_URL


volumes:
  pgdata:

networks:
  iceteabot:
    driver: bridge